const volatileMissionNodes = [
  {
    Planet: "Venus Proxima",
    Name: "Beacon Shield Ring",
    Faction: "Corpus",
    CreditReward: 2600,
    AdditionalCreditReward: 33750,
    DropTableAlias: "VenusProximaVolatile",
    Level: "17 - 20",
    TileSet: "Free Space",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Sovereign Grasp",
    Faction: "Corpus",
    CreditReward: 4200,
    AdditionalCreditReward: 75000,
    DropTableAlias: "NeptuneProximaVolatile",
    Level: "33 - 36",
    TileSet: "Free Space",
  },
  {
    Planet: "Pluto Proxima",
    Name: "Profit Margin",
    Faction: "Corpus",
    CreditReward: 5000,
    AdditionalCreditReward: 110000,
    DropTableAlias: "PlutoProximaVolatile",
    Level: "41 - 44",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Numina",
    Faction: "Corpus",
    CreditReward: 5700,
    AdditionalCreditReward: 131250,
    DropTableAlias: "VeilProximaVolatile",
    Level: "48 - 52",
    TileSet: "Free Space",
  },
];

const survivalMissionNodes = [
  {
    Planet: "Venus",
    Name: "V Prime",
    Faction: "Corpus",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival",
    Level: "3 - 8",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Mercury",
    Name: "Apollodorus",
    Faction: "Infested",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival",
    Level: "6 - 11",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Venus",
    Name: "Malva (Dark Sector)",
    Faction: "Infested",
    CreditReward: 1700,
    AdditionalCreditReward: 10000,
    DropTableAlias: "DSSurvival1",
    Level: "8 - 18",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Phobos",
    Name: "Stickney",
    Faction: "Corpus",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival",
    Level: "10 - 15",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Mars",
    Name: "Wahiba (Dark Sector)",
    Faction: "Infested",
    CreditReward: 1900,
    AdditionalCreditReward: 14000,
    DropTableAlias: "DSSurvival2",
    Level: "10 - 20",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Ceres",
    Name: "Draco",
    Faction: "Grineer",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival2",
    Level: "12 - 17",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Jupiter",
    Name: "Elara",
    Faction: "Corpus",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival2",
    Level: "15 - 20",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Phobos",
    Name: "Zeugma (Dark Sector)",
    Faction: "Infested",
    CreditReward: 2400,
    AdditionalCreditReward: 16000,
    DropTableAlias: "DSSurvival2",
    Level: "15 - 25",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Ceres",
    Name: "Gabii (Dark Sector)",
    Faction: "Infested",
    CreditReward: 2400,
    AdditionalCreditReward: 20000,
    DropTableAlias: "DSSurvival1",
    Level: "15 - 25",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Void",
    Name: "Ani",
    Faction: "Corrupted",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidSurvival2",
    Level: "20 - 25",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Jupiter",
    Name: "Cameria (Dark Sector)",
    Faction: "Infested",
    CreditReward: 2900,
    AdditionalCreditReward: 14000,
    DropTableAlias: "DSSurvival2",
    Level: "20 - 30",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Saturn",
    Name: "Titan",
    Faction: "Grineer",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival2",
    Level: "21 - 26",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Venus Proxima",
    Name: "Luckless Expanse",
    Faction: "Corpus",
    CreditReward: 3100,
    AdditionalCreditReward: 41250,
    DropTableAlias: "VenusProximaSurvival",
    Level: "22 - 25",
    TileSet: "Free Space",
  },
  {
    Planet: "Uranus",
    Name: "Ophelia",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival3",
    Level: "24 - 29",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Lua",
    Name: "Tycho",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival3",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Lua",
    Name: "Yuvarium",
    Faction: "Corrupted",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "ConjunctionSurvival",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Europa",
    Name: "Archaeo-freighter",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival", // Assuming "Survival" as a default
    Level: "25 - 30",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Deimos",
    Name: "Terrorem",
    Faction: "Infested",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "DerelictSurvival",
    Level: "25 - 35",
    TileSet: "Orokin Derelict",
  },
  {
    Planet: "Uranus",
    Name: "Assur (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3400,
    AdditionalCreditReward: 16000,
    DropTableAlias: "DSSurvival3",
    Level: "25 - 35",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Saturn",
    Name: "Piscinas (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3500,
    AdditionalCreditReward: 14000,
    DropTableAlias: "DSSurvival2",
    Level: "26 - 36",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Enkidu Ice Drifts",
    Faction: "Corpus",
    CreditReward: 3800,
    AdditionalCreditReward: 62500,
    DropTableAlias: "NeptuneProximaSurvival",
    Level: "29 - 32",
    TileSet: "Free Space",
  },
  {
    Planet: "Pluto",
    Name: "Palus",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival3",
    Level: "30 - 40",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Sedna",
    Name: "Selkie",
    Faction: "Grineer",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival3",
    Level: "30 - 40",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Neptune",
    Name: "Kelashin (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 18000,
    DropTableAlias: "DSSurvival3",
    Level: "30 - 40",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Eris",
    Name: "Nimus",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Survival3",
    Level: "30 - 40",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Taveuni",
    Faction: "Grineer",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "KuvaSurvival",
    Level: "32 - 37",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Sedna",
    Name: "Amarna (Dark Sector)",
    Faction: "Infested",
    CreditReward: 4400,
    AdditionalCreditReward: 16000,
    DropTableAlias: "DSSurvival3",
    Level: "35 - 45",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Eris",
    Name: "Zabala (Dark Sector)",
    Faction: "Infested",
    CreditReward: 4400,
    AdditionalCreditReward: 18000,
    DropTableAlias: "DSSurvival4",
    Level: "35 - 45",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Pluto Proxima",
    Name: "Fenton's Field",
    Faction: "Corpus",
    CreditReward: 4900,
    AdditionalCreditReward: 100000,
    DropTableAlias: "PlutoProximaSurvival",
    Level: "40 - 43",
    TileSet: "Free Space",
  },
  {
    Planet: "Void",
    Name: "Mot",
    Faction: "Corrupted",
    CreditReward: 4900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidSurvival4",
    Level: "40 - 45",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Veil Proxima",
    Name: "Lu-yan",
    Faction: "Corpus",
    CreditReward: 6400,
    AdditionalCreditReward: 150000,
    DropTableAlias: "VeilProximaSurvival",
    Level: "55 - 59",
    TileSet: "Free Space",
  },
  {
    Planet: "Deimos",
    Name: "Persto",
    Faction: "The Murmur",
    CreditReward: 6400,
    AdditionalCreditReward: 0,
    DropTableAlias: "EntratiSurvival",
    Level: "55 - 60",
    TileSet: "Albrecht's Laboratories",
  },
  {
    Planet: "Lua",
    Name: "Circulus",
    Faction: "Corrupted",
    CreditReward: 8900,
    AdditionalCreditReward: 0,
    DropTableAlias: "ConjunctionSurvival2",
    Level: "80 - 100",
    TileSet: "Orokin Moon",
  },
];

const spyMissionNodes = [
  {
    Planet: "Earth",
    Name: "Cambria",
    Faction: "Grineer",
    CreditReward: 1100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy1",
    Level: "2 - 4",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Unda",
    Faction: "Corpus",
    CreditReward: 1300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy1",
    Level: "4 - 6",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Mercury",
    Name: "Suisei",
    Faction: "Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy1",
    Level: "8 - 10",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Mars",
    Name: "Arval",
    Faction: "Grineer",
    CreditReward: 1800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy1",
    Level: "9 - 11",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Phobos",
    Name: "Shklovsky",
    Faction: "Corpus",
    CreditReward: 2000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy1",
    Level: "11 - 13",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Ceres",
    Name: "Bode",
    Faction: "Grineer",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy2",
    Level: "12 - 14",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Jupiter",
    Name: "Amalthea",
    Faction: "Corpus",
    CreditReward: 2600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy2",
    Level: "17 - 19",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Valac",
    Faction: "Grineer/Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy2",
    Level: "18 - 20",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Venus Proxima",
    Name: "Orvin-Haarc",
    Faction: "Corpus",
    CreditReward: 2800,
    AdditionalCreditReward: 37500,
    DropTableAlias: "VenusProximaSpy",
    Level: "19 - 22",
    TileSet: "Free Space",
  },
  {
    Planet: "Saturn",
    Name: "Dione",
    Faction: "Grineer",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy2",
    Level: "21 - 23",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Lua",
    Name: "Pavlov",
    Faction: "Grineer/Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "LuaSpy",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Uranus",
    Name: "Rosalind",
    Faction: "Grineer",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy3",
    Level: "27 - 29",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Neptune",
    Name: "Nereid",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy3",
    Level: "30 - 32",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Pago",
    Faction: "Grineer",
    CreditReward: 4000,
    AdditionalCreditReward: 0,
    DropTableAlias: "KuvaSpy",
    Level: "31 - 33",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Brom Cluster",
    Faction: "Corpus",
    CreditReward: 4100,
    AdditionalCreditReward: 75000,
    DropTableAlias: "NeptuneProximaSpy",
    Level: "32 - 35",
    TileSet: "Free Space",
  },
  {
    Planet: "Pluto",
    Name: "Oceanum",
    Faction: "Corpus",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy3",
    Level: "32 - 36",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Sedna",
    Name: "Kelpie",
    Faction: "Grineer",
    CreditReward: 4400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Spy3",
    Level: "35 - 40",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Pluto Proxima",
    Name: "Peregrine Axis",
    Faction: "Corpus",
    CreditReward: 5200,
    AdditionalCreditReward: 120000,
    DropTableAlias: "PlutoProximaSpy",
    Level: "43 - 46",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Sabmir Cloud",
    Faction: "Corpus",
    CreditReward: 6600,
    AdditionalCreditReward: 150000,
    DropTableAlias: "VeilProximaSpy",
    Level: "57 - 60",
    TileSet: "Free Space",
  },
];

const skirmishMissionNodes = [
  {
    Planet: "Earth Proxima",
    Name: "Sover Strait",
    Faction: "Grineer",
    CreditReward: 2400,
    AdditionalCreditReward: 32000,
    DropTableAlias: "EarthProximaSkirmish",
    Level: "15 - 20",
    TileSet: "Free Space",
  },
  {
    Planet: "Earth Proxima",
    Name: "Iota Temple",
    Faction: "Grineer",
    CreditReward: 2900,
    AdditionalCreditReward: 38000,
    DropTableAlias: "EarthProximaSkirmish",
    Level: "20 - 28",
    TileSet: "Free Space",
  },
  {
    Planet: "Earth Proxima",
    Name: "Ogal Cluster",
    Faction: "Grineer",
    CreditReward: 3000,
    AdditionalCreditReward: 42500,
    DropTableAlias: "EarthProximaSkirmish",
    Level: "21 - 26",
    TileSet: "Free Space",
  },
  {
    Planet: "Earth Proxima",
    Name: "Korm's Belt",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 45000,
    DropTableAlias: "EarthProximaSkirmish",
    Level: "24 - 30",
    TileSet: "Free Space",
  },
  {
    Planet: "Earth Proxima",
    Name: "Bendar Cluster",
    Faction: "Grineer",
    CreditReward: 3800,
    AdditionalCreditReward: 45000,
    DropTableAlias: "EarthProximaSkirmish",
    Level: "29 - 36",
    TileSet: "Free Space",
  },
  {
    Planet: "Saturn Proxima",
    Name: "Lupal Pass",
    Faction: "Grineer",
    CreditReward: 5700,
    AdditionalCreditReward: 50000,
    DropTableAlias: "SaturnProximaSkirmish",
    Level: "48 - 56",
    TileSet: "Free Space",
  },
  {
    Planet: "Saturn Proxima",
    Name: "Nodo Gap",
    Faction: "Grineer",
    CreditReward: 6300,
    AdditionalCreditReward: 50000,
    DropTableAlias: "SaturnProximaSkirmish",
    Level: "54 - 60",
    TileSet: "Free Space",
  },
  {
    Planet: "Saturn Proxima",
    Name: "Mordo Cluster",
    Faction: "Grineer",
    CreditReward: 6400,
    AdditionalCreditReward: 50000,
    DropTableAlias: "SaturnProximaSkirmish",
    Level: "55 - 60",
    TileSet: "Free Space",
  },
  {
    Planet: "Saturn Proxima",
    Name: "Vand Cluster",
    Faction: "Grineer",
    CreditReward: 7400,
    AdditionalCreditReward: 70000,
    DropTableAlias: "SaturnProximaSkirmish",
    Level: "65 - 70",
    TileSet: "Free Space",
  },
  {
    Planet: "Saturn Proxima",
    Name: "Kasio's Rest",
    Faction: "Grineer",
    CreditReward: 7900,
    AdditionalCreditReward: 75000,
    DropTableAlias: "SaturnProximaSkirmish",
    Level: "70 - 75",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Flexa",
    Faction: "Grineer",
    CreditReward: 8900,
    AdditionalCreditReward: 85000,
    DropTableAlias: "VeilProximaSkirmish",
    Level: "80 - 90",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "H-2 Cloud",
    Faction: "Grineer",
    CreditReward: 8900,
    AdditionalCreditReward: 135000,
    DropTableAlias: "VeilProximaSkirmish",
    Level: "80 - 90",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "R-9 Cloud",
    Faction: "Grineer",
    CreditReward: 8900,
    AdditionalCreditReward: 115000,
    DropTableAlias: "VeilProximaSkirmish",
    Level: "80 - 90",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Nsu Grid",
    Faction: "Grineer",
    CreditReward: 8900,
    AdditionalCreditReward: 80000,
    DropTableAlias: "VeilProximaSkirmish",
    Level: "80 - 90",
    TileSet: "Free Space",
  },
];

const sabotageMissionNodes = [
  {
    Planet: "Earth",
    Name: "Cervantes",
    Faction: "Grineer",
    CreditReward: 1300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "4 - 6",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Ishtar",
    Faction: "Corpus",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "6 - 8",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Mercury",
    Name: "Terminus",
    Faction: "Infested/Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "8 - 10",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Mars",
    Name: "Ares",
    Faction: "Grineer",
    CreditReward: 1800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "9 - 11",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Mars",
    Name: "Gradivus",
    Faction: "Corpus",
    CreditReward: 1800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "9 - 11",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Deimos",
    Name: "Formido",
    Faction: "Infested",
    CreditReward: 2300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "14 - 16",
    TileSet: "Orokin Derelict",
  },
  {
    Planet: "Ceres",
    Name: "Ker",
    Faction: "Grineer",
    CreditReward: 2300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "14 - 16",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Ceres",
    Name: "Thon",
    Faction: "Grineer",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "15 - 17",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Jupiter",
    Name: "Galilea",
    Faction: "Corpus",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "AWSabotage",
    Level: "15 - 20",
    TileSet: "Corpus Ship (Archwing)",
  },
  {
    Planet: "Jupiter",
    Name: "Adrastea",
    Faction: "Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "18 - 20",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Jupiter",
    Name: "Thebe",
    Faction: "Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "18 - 20",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Kokabiel",
    Faction: "Corpus",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "20 - 22",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Void",
    Name: "Stribog",
    Faction: "Corrupted",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidSabotage2",
    Level: "20 - 25",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Saturn",
    Name: "Enceladus",
    Faction: "Grineer",
    CreditReward: 3200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "23 - 25",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Saturn",
    Name: "Calypso",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "24 - 26",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Uranus",
    Name: "Desdemona",
    Faction: "Grineer",
    CreditReward: 3500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "26 - 28",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Neptune",
    Name: "Sao",
    Faction: "Corpus",
    CreditReward: 3800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "29 - 31",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Eris",
    Name: "Naeglar",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "30 - 34",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Sedna",
    Name: "Rusalka",
    Faction: "Grineer",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "32 - 36",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Pluto",
    Name: "Cypress",
    Faction: "Corpus",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Sabotage", // Assuming "Sabotage" as a default
    Level: "34 - 38",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Void",
    Name: "Marduk",
    Faction: "Corrupted",
    CreditReward: 4900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidSabotage4",
    Level: "40 - 45",
    TileSet: "Orokin Tower",
  },
];

const rescueMissionNodes = [
  {
    Planet: "Earth",
    Name: "Pacific",
    Faction: "Grineer",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue1",
    Level: "3 - 6",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Venus",
    Name: "Linea",
    Faction: "Corpus",
    CreditReward: 1400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue1",
    Level: "5 - 7",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Mercury",
    Name: "Caloris",
    Faction: "Grineer",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue1",
    Level: "6 - 8",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Mars",
    Name: "Martialis",
    Faction: "Grineer",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue1",
    Level: "10 - 12",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Ceres",
    Name: "Nuovo",
    Faction: "Grineer",
    CreditReward: 2200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue1",
    Level: "13 - 15",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Phobos",
    Name: "Monolith",
    Faction: "Corpus",
    CreditReward: 2200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue1",
    Level: "13 - 15",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Jupiter",
    Name: "Metis",
    Faction: "Corpus",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue2",
    Level: "15 - 17",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Orias",
    Faction: "Corpus",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue2",
    Level: "20 - 22",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Saturn",
    Name: "Numa",
    Faction: "Grineer",
    CreditReward: 3100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue2",
    Level: "22 - 24",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Saturn",
    Name: "Anthe",
    Faction: "Grineer",
    CreditReward: 3100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "22 - 24",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Uranus",
    Name: "Caliban",
    Faction: "Grineer",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "25 - 27",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Lua",
    Name: "Zeipel",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Neptune",
    Name: "Triton",
    Faction: "Corpus",
    CreditReward: 3700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "28 - 30",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Sedna",
    Name: "Naga",
    Faction: "Grineer",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "30 - 34",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Garus",
    Faction: "Grineer",
    CreditReward: 4000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "31 - 33",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Eris",
    Name: "Brugia",
    Faction: "Infested",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "32 - 36",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Pluto",
    Name: "Regna",
    Faction: "Corpus",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Rescue3",
    Level: "34 - 38",
    TileSet: "Corpus Outpost",
  },
];

const orphixMissionNodes = [
  {
    Planet: "Venus Proxima",
    Name: "Vesper Strait",
    Faction: "Corpus",
    CreditReward: 3000,
    AdditionalCreditReward: 41250,
    DropTableAlias: "VenusProximaOrphix",
    Level: "21 - 24",
    TileSet: "Free Space",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Mammon's Prospect",
    Faction: "Corpus",
    CreditReward: 4000,
    AdditionalCreditReward: 68750,
    DropTableAlias: "NeptuneProximaOrphix",
    Level: "31 - 34",
    TileSet: "Free Space",
  },
  {
    Planet: "Pluto Proxima",
    Name: "Khufu Envoy",
    Faction: "Corpus",
    CreditReward: 4400,
    AdditionalCreditReward: 80000,
    DropTableAlias: "PlutoProximaOrphix",
    Level: "35 - 38",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Erato",
    Faction: "Corpus",
    CreditReward: 6300,
    AdditionalCreditReward: 143750,
    DropTableAlias: "VeilProximaOrphix",
    Level: "54 - 58",
    TileSet: "Free Space",
  },
];

const mobileDefenseMissionNodes = [
  {
    Planet: "Earth",
    Name: "Erpo",
    Faction: "Grineer",
    CreditReward: 1000,
    AdditionalCreditReward: 0,
    DropTableAlias: "AWMobileDefense",
    Level: "1 - 6",
    TileSet: "Free Space",
  },
  {
    Planet: "Earth",
    Name: "Eurasia",
    Faction: "Grineer",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "3 - 5",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Aphrodite",
    Faction: "Corpus",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "6 - 8",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Mars",
    Name: "Tharsis",
    Faction: "Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "8 - 10",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Mercury",
    Name: "Boethius",
    Faction: "Infested",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "8 - 10",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Mars",
    Name: "Vallis",
    Faction: "Grineer",
    CreditReward: 2000,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "11 - 13",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Phobos",
    Name: "Sharpless",
    Faction: "Corpus",
    CreditReward: 2000,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "11 - 13",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Ceres",
    Name: "Kiste",
    Faction: "Grineer",
    CreditReward: 2200,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "13 - 15",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Deimos",
    Name: "Dirus",
    Faction: "Infested",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "15 - 17",
    TileSet: "Orokin Derelict",
  },
  {
    Planet: "Jupiter",
    Name: "Carme",
    Faction: "Corpus",
    CreditReward: 2500,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "16 - 18",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Morax",
    Faction: "Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "18 - 20",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Void",
    Name: "Tiwaz",
    Faction: "Corrupted",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidMobileDefense2",
    Level: "20 - 25",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Saturn",
    Name: "Keeler",
    Faction: "Grineer",
    CreditReward: 3200,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "23 - 25",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Lua",
    Name: "Grimaldi",
    Faction: "Grineer",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Uranus",
    Name: "Cressida",
    Faction: "Grineer",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "27 - 29",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Neptune",
    Name: "Salacia",
    Faction: "Corpus",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "AWMobileDefense",
    Level: "27 - 32",
    TileSet: "Corpus Ship (Archwing)",
  },
  {
    Planet: "Neptune",
    Name: "Larissa",
    Faction: "Corpus",
    CreditReward: 3800,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "29 - 31",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Rotuma",
    Faction: "Grineer",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "30 - 32",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Pluto",
    Name: "Minthe",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "30 - 34",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Eris",
    Name: "Solium",
    Faction: "Infested",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "34 - 38",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Sedna",
    Name: "Charybdis",
    Faction: "Grineer",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "MobileDefense", // Assuming "MobileDefense" as a default
    Level: "34 - 38",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Void",
    Name: "Aten",
    Faction: "Corrupted",
    CreditReward: 4900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidMobileDefense4",
    Level: "40 - 45",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Zariman Ten Zero",
    Name: "The Greenway",
    Faction: "Grineer or Corpus",
    CreditReward: 5900,
    AdditionalCreditReward: 0,
    DropTableAlias: "ZarimanMobileDefense",
    Level: "50 - 55",
    TileSet: "Zariman (Tileset)",
  },
];

const interceptionMissionNodes = [
  {
    Planet: "Earth",
    Name: "Gaia",
    Faction: "Grineer",
    CreditReward: 1000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception1",
    Level: "1 - 6",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Cytherean",
    Faction: "Corpus",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception1",
    Level: "3 - 8",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Mercury",
    Name: "Odin",
    Faction: "Grineer",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception1",
    Level: "6 - 11",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Mars",
    Name: "Alator",
    Faction: "Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception1",
    Level: "8 - 13",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Ceres",
    Name: "Cinxia",
    Faction: "Grineer",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception1",
    Level: "12 - 17",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Jupiter",
    Name: "Callisto",
    Faction: "Corpus",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception2",
    Level: "15 - 20",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Ose",
    Faction: "Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception2",
    Level: "18 - 23",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Saturn",
    Name: "Rhea",
    Faction: "Grineer",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception2",
    Level: "21 - 26",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Uranus",
    Name: "Caelus",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    DropTableAlias: "AWInterception",
    Level: "24 - 29",
    TileSet: "Free Space",
  },
  {
    Planet: "Uranus",
    Name: "Umbriel",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception2",
    Level: "24 - 29",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Pluto",
    Name: "Cerberus",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception3",
    Level: "30 - 40",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Eris",
    Name: "Xini",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception3",
    Level: "30 - 40",
    TileSet: "Corpus Ship", // Note: Original data said "Corpus Ship" for Infested, which is unusual. Kept as is.
  },
  {
    Planet: "Sedna",
    Name: "Berehynia",
    Faction: "Grineer",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Interception3",
    Level: "30 - 40",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Void",
    Name: "Mithra",
    Faction: "Corrupted",
    CreditReward: 4900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidInterception4",
    Level: "40 - 45",
    TileSet: "Orokin", // Note: Original data ended with "Orokin". Assuming "Orokin Tower" based on other Void nodes.
  },
];

const hijackMissionNodes = [
  {
    Planet: "Ceres",
    Name: "Ludi",
    Faction: "Grineer",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Hijack",
    Level: "15 - 17",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Europa",
    Name: "Sorath",
    Faction: "Corpus",
    CreditReward: 2800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Hijack",
    Level: "19 - 21",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Sedna",
    Name: "Marid",
    Faction: "Grineer",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Hijack",
    Level: "34 - 38",
    TileSet: "Grineer Shipyard",
  },
];

const exterminateMissionNodes = [
  {
    Planet: "Earth",
    Name: "E Prime",
    Faction: "Grineer",
    CreditReward: 1000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "1 - 3",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Earth",
    Name: "Mariana",
    Faction: "Grineer",
    CreditReward: 1000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "1 - 3",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Venus",
    Name: "E Gate",
    Faction: "Corpus",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "3 - 5",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Venus",
    Name: "Montes",
    Faction: "Corpus",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "AWExterminate",
    Level: "3 - 8",
    TileSet: "Corpus Ship (Archwing)",
  },
  {
    Planet: "Mercury",
    Name: "Pantheon",
    Faction: "Grineer",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "6 - 8",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Mercury",
    Name: "M Prime",
    Faction: "Infested/Grineer",
    CreditReward: 1600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "7 - 9",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Mars",
    Name: "Hellas",
    Faction: "Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "8 - 10",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Mars",
    Name: "Syrtis",
    Faction: "Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "AWExterminate",
    Level: "8 - 13",
    TileSet: "Free Space",
  },
  {
    Planet: "Phobos",
    Name: "Roche",
    Faction: "Corpus",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "10 - 12",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Void",
    Name: "Teshub",
    Faction: "Corrupted",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidExterminate1",
    Level: "10 - 15",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Mars",
    Name: "Ultor",
    Faction: "Grineer/Corpus",
    CreditReward: 2000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "11 - 13",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Ceres",
    Name: "Pallas",
    Faction: "Grineer",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "12 - 14",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Deimos",
    Name: "Phlegyas",
    Faction: "Infested",
    CreditReward: 2200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate1",
    Level: "13 - 15",
    TileSet: "Orokin Derelict",
  },
  {
    Planet: "Venus Proxima",
    Name: "Bifrost Echo",
    Faction: "Corpus",
    CreditReward: 2400,
    AdditionalCreditReward: 30000,
    DropTableAlias: "VenusProximaExterminate",
    Level: "15 - 18",
    TileSet: "Free Space",
  },
  {
    Planet: "Jupiter",
    Name: "Carpo",
    Faction: "Corpus",
    CreditReward: 2600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "17 - 19",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Armaros",
    Faction: "Infested/Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "18 - 20",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Europa",
    Name: "Baal",
    Faction: "Corpus",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "21 - 23",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Saturn",
    Name: "Telesto",
    Faction: "Grineer",
    CreditReward: 3100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "22 - 24",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Uranus",
    Name: "Sycorax",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "24 - 26",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Lua",
    Name: "Plato",
    Faction: "Grineer/Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Uranus",
    Name: "Puck",
    Faction: "Grineer",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "27 - 29",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Nu-gua Mines",
    Faction: "Corpus",
    CreditReward: 3600,
    AdditionalCreditReward: 56250,
    DropTableAlias: "NeptuneProximaExterminate",
    Level: "27 - 30",
    TileSet: "Free Space",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Dakata",
    Faction: "Grineer",
    CreditReward: 3700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate2",
    Level: "28 - 30",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Neptune",
    Name: "Neso",
    Faction: "Corpus",
    CreditReward: 3800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate3",
    Level: "29 - 31",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Void",
    Name: "Oxomoco",
    Faction: "Corrupted",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidExterminate3",
    Level: "30 - 35",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Pluto",
    Name: "Narcissus",
    Faction: "Corpus",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate3",
    Level: "32 - 36",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Sedna",
    Name: "Adaro",
    Faction: "Grineer",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate3",
    Level: "32 - 36",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Eris",
    Name: "Saxis",
    Faction: "Infested",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate3",
    Level: "34 - 38",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Pluto",
    Name: "Acheron",
    Faction: "Corpus",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate3",
    Level: "34 - 38",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Pluto Proxima",
    Name: "Seven Sirens",
    Faction: "Corpus",
    CreditReward: 4600,
    AdditionalCreditReward: 90000,
    DropTableAlias: "PlutoProximaExterminate",
    Level: "37 - 40",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Calabash",
    Faction: "Corpus",
    CreditReward: 5400,
    AdditionalCreditReward: 125000,
    DropTableAlias: "VeilProximaExterminate",
    Level: "45 - 49",
    TileSet: "Free Space",
  },
  {
    Planet: "Zariman Ten Zero",
    Name: "Halako Perimeter",
    Faction: "Grineer or Corpus",
    CreditReward: 5900,
    AdditionalCreditReward: 0,
    DropTableAlias: "ZarimanExterminate",
    Level: "50 - 55",
    TileSet: "Zariman (Tileset)",
  },
  {
    Planet: "Deimos",
    Name: "Nex",
    Faction: "The Murmur",
    CreditReward: 6400,
    AdditionalCreditReward: 0,
    DropTableAlias: "EntratiExterminate",
    Level: "55 - 60",
    TileSet: "Albrecht's Laboratories",
  },
  {
    Planet: "Höllvania",
    Name: "Mausoleum East",
    Faction: "Scaldra",
    CreditReward: 7400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate",
    Level: "65 - 70",
    TileSet: "Höllvania",
  },
  {
    Planet: "Höllvania",
    Name: "Rhu Manor",
    Faction: "Techrot",
    CreditReward: 7400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Exterminate",
    Level: "65 - 70",
    TileSet: "Höllvania",
  },
];

const faceoffMissionNodes = [
  {
    Planet: "Höllvania",
    Name: "Vehrvod District",
    Faction: "Scaldra",
    CreditReward: 7400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Faceoff",
    Level: "65 - 70",
    TileSet: "Höllvania",
  },
  {
    Planet: "Höllvania",
    Name: "Lower Vehrvod",
    Faction: "Scaldra",
    CreditReward: 7400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Faceoff",
    Level: "65 - 70",
    TileSet: "Höllvania",
  },
];

const excavationMissionNodes = [
  {
    Planet: "Earth",
    Name: "Everest",
    Faction: "Grineer",
    CreditReward: 1000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Excavation1",
    Level: "1 - 6",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Kiliken",
    Faction: "Corpus",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Excavation1",
    Level: "3 - 8",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Earth",
    Name: "Tikal (Dark Sector)",
    Faction: "Infested",
    CreditReward: 1500,
    AdditionalCreditReward: 12000,
    DropTableAlias: "Excavation1",
    Level: "6 - 16",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Mars",
    Name: "Augustus",
    Faction: "Grineer",
    CreditReward: 1800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Excavation1",
    Level: "9 - 14",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Europa",
    Name: "Valefor",
    Faction: "Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Excavation2",
    Level: "18 - 23",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Europa",
    Name: "Cholistan (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3200,
    AdditionalCreditReward: 16000,
    DropTableAlias: "Excavation3",
    Level: "23 - 33",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Europa",
    Name: "Mines of Karishh",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "",
    Level: "25 - 30",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Neptune",
    Name: "Despina",
    Faction: "Corpus",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Excavation3",
    Level: "27 - 32",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Pluto",
    Name: "Hieracon (Dark Sector)",
    Faction: "Infested",
    CreditReward: 4400,
    AdditionalCreditReward: 20000,
    DropTableAlias: "Excavation3",
    Level: "35 - 45",
    TileSet: "Corpus Outpost",
  },
];

const disruptionMissionNodes = [
  {
    Planet: "Mars",
    Name: "Olympus",
    Faction: "Grineer",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "DisruptionMars",
    Level: "15 - 20",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Neptune",
    Name: "Laomedeia",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "DisruptionNeptune",
    Level: "25 - 30",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Jupiter",
    Name: "Ganymede",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "DisruptionJupiter",
    Level: "30 - 35",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Uranus",
    Name: "Ur (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 16000,
    DropTableAlias: "DisruptionUranus",
    Level: "30 - 35",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Sedna",
    Name: "Kappa",
    Faction: "Grineer",
    CreditReward: 4300,
    AdditionalCreditReward: 0,
    DropTableAlias: "DisruptionSedna",
    Level: "34 - 38",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Lua",
    Name: "Apollo",
    Faction: "Corpus",
    CreditReward: 4400,
    AdditionalCreditReward: 0,
    DropTableAlias: "DisruptionLua",
    Level: "35 - 40",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Tamu",
    Faction: "Grineer",
    CreditReward: 4400,
    AdditionalCreditReward: 0,
    DropTableAlias: "DisruptionKuva",
    Level: "35 - 40",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Deimos",
    Name: "Armatus",
    Faction: "The Murmur",
    CreditReward: 6400,
    AdditionalCreditReward: 0,
    DropTableAlias: "EntratiDisruption",
    Level: "55 - 60",
    TileSet: "Albrecht's Laboratories",
  },
];

const defectionMissionNodes = [
  {
    Planet: "Phobos",
    Name: "Memphis (Dark Sector)",
    Faction: "Infested",
    CreditReward: 2400,
    AdditionalCreditReward: 16000,
    DropTableAlias: "Defection1",
    Level: "15 - 25",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Saturn",
    Name: "Caracol (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3500,
    AdditionalCreditReward: 14000,
    DropTableAlias: "Defection2",
    Level: "26 - 36",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Neptune",
    Name: "Yursa (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 18000,
    DropTableAlias: "Defection3",
    Level: "30 - 40",
    TileSet: "Infested Ship",
  },
];

const defenseMissionNodes = [
  {
    Planet: "Earth",
    Name: "Lith",
    Faction: "Grineer",
    CreditReward: 1000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense1",
    Level: "1 - 6",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Tessera",
    Faction: "Corpus",
    CreditReward: 1200,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense1",
    Level: "3 - 8",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Mercury",
    Name: "Lares",
    Faction: "Infested",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense1",
    Level: "6 - 11",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Earth",
    Name: "Coba (Dark Sector)",
    Faction: "Infested",
    CreditReward: 1500,
    AdditionalCreditReward: 12000,
    DropTableAlias: "DSDefense",
    Level: "6 - 16",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Mars",
    Name: "Spear",
    Faction: "Grineer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense1",
    Level: "8 - 13",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Venus",
    Name: "Romula (Dark Sector)",
    Faction: "Infested",
    CreditReward: 1700,
    AdditionalCreditReward: 10000,
    DropTableAlias: "DSDefense",
    Level: "8 - 18",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Phobos",
    Name: "Gulliver",
    Faction: "Corpus",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense1",
    Level: "10 - 15",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Void",
    Name: "Taranis",
    Faction: "Corrupted",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidDefense1",
    Level: "10 - 15",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Mars",
    Name: "Kadesh (Dark Sector)",
    Faction: "Infested",
    CreditReward: 1900,
    AdditionalCreditReward: 14000,
    DropTableAlias: "DSDefense",
    Level: "10 - 20",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Ceres",
    Name: "Casta",
    Faction: "Grineer",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense1",
    Level: "12 - 17",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Jupiter",
    Name: "Io",
    Faction: "Corpus",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense2",
    Level: "15 - 20",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Deimos",
    Name: "Hyf",
    Faction: "Infested",
    CreditReward: 2400,
    AdditionalCreditReward: 0,
    DropTableAlias: "DerelictDefense",
    Level: "15 - 20",
    TileSet: "Orokin Derelict",
  },
  {
    Planet: "Ceres",
    Name: "Seimeni (Dark Sector)",
    Faction: "Infested",
    CreditReward: 2400,
    AdditionalCreditReward: 20000,
    DropTableAlias: "DSDefense",
    Level: "15 - 25",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Europa",
    Name: "Paimon",
    Faction: "Corpus",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense2",
    Level: "18 - 23",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Jupiter",
    Name: "Sinai (Dark Sector)",
    Faction: "Infested",
    CreditReward: 2900,
    AdditionalCreditReward: 14000,
    DropTableAlias: "DSDefense",
    Level: "20 - 30",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Saturn",
    Name: "Helene",
    Faction: "Grineer",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense2",
    Level: "21 - 26",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Venus Proxima",
    Name: "Falling Glory",
    Faction: "Corpus",
    CreditReward: 3200,
    AdditionalCreditReward: 45000,
    DropTableAlias: "VenusProximaDefense",
    Level: "23 - 26",
    TileSet: "Free Space",
  },
  {
    Planet: "Europa",
    Name: "Larzac (Dark Sector)",
    Faction: "Infested",
    CreditReward: 3200,
    AdditionalCreditReward: 16000,
    DropTableAlias: "DSDefense",
    Level: "23 - 33",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Uranus",
    Name: "Stephano",
    Faction: "Grineer",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "24 - 29",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Arva Vector",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 50000,
    DropTableAlias: "NeptuneProximaDefense",
    Level: "25 - 28",
    TileSet: "Free Space",
  },
  {
    Planet: "Europa",
    Name: "Icefields of Riddah",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "",
    Level: "25 - 30",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Lua",
    Name: "Stöfler",
    Faction: "Grineer",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Neptune",
    Name: "Proteus",
    Faction: "Corpus",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "27 - 32",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Kuva Fortress",
    Name: "Nabuk",
    Faction: "Grineer",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "30 - 32",
    TileSet: "Grineer Asteroid Fortress",
  },
  {
    Planet: "Void",
    Name: "Belenus",
    Faction: "Corrupted",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidDefense3",
    Level: "30 - 35",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Sedna",
    Name: "Hydron",
    Faction: "Grineer",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "30 - 40",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Pluto",
    Name: "Outer Terminus",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "30 - 40",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Eris",
    Name: "Kala-azar",
    Faction: "Infested",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Defense3",
    Level: "30 - 40",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Sedna",
    Name: "Sangeru (Dark Sector)",
    Faction: "Infested",
    CreditReward: 4400,
    AdditionalCreditReward: 16000,
    DropTableAlias: "DSDefense",
    Level: "35 - 45",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Pluto",
    Name: "Sechura (Dark Sector)",
    Faction: "Infested",
    CreditReward: 4400,
    AdditionalCreditReward: 20000,
    DropTableAlias: "DSDefense",
    Level: "35 - 45",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Eris",
    Name: "Akkad (Dark Sector)",
    Faction: "Infested",
    CreditReward: 4400,
    AdditionalCreditReward: 18000,
    DropTableAlias: "DSDefense",
    Level: "35 - 45",
    TileSet: "Infested Ship",
  },
  {
    Planet: "Pluto Proxima",
    Name: "Obol Crossing",
    Faction: "Corpus",
    CreditReward: 4800,
    AdditionalCreditReward: 100000,
    DropTableAlias: "PlutoProximaDefense",
    Level: "39 - 42",
    TileSet: "Free Space",
  },
  {
    Planet: "Veil Proxima",
    Name: "Arc Silver",
    Faction: "Corpus",
    CreditReward: 6000,
    AdditionalCreditReward: 137500,
    DropTableAlias: "VeilProximaDefense",
    Level: "51 - 55",
    TileSet: "Free Space",
  },
];

const captureMissionNodes = [
  {
    Planet: "Earth",
    Name: "Mantle",
    Faction: "Grineer",
    CreditReward: 1100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "2 - 4",
    TileSet: "Grineer Forest",
  },
  {
    Planet: "Venus",
    Name: "Venera",
    Faction: "Corpus",
    CreditReward: 1400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "5 - 7",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Mercury",
    Name: "Elion",
    Faction: "Grineer",
    CreditReward: 1600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "7 - 9",
    TileSet: "Grineer Asteroid",
  },
  {
    Planet: "Mars",
    Name: "Ara",
    Faction: "Grineer",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "10 - 12",
    TileSet: "Grineer Settlement",
  },
  {
    Planet: "Void",
    Name: "Hepit",
    Faction: "Corrupted",
    CreditReward: 1900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidCapture1",
    Level: "10 - 15",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Phobos",
    Name: "Skyresh",
    Faction: "Corpus",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "12 - 14",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Deimos",
    Name: "Horend",
    Faction: "Infested",
    CreditReward: 2100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "12 - 14",
    TileSet: "Orokin Derelict",
  },
  {
    Planet: "Ceres",
    Name: "Lex",
    Faction: "Grineer",
    CreditReward: 2300,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "14 - 16",
    TileSet: "Grineer Shipyard",
  },
  {
    Planet: "Jupiter",
    Name: "Ananke",
    Faction: "Corpus",
    CreditReward: 2500,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "16 - 18",
    TileSet: "Corpus Gas City",
  },
  {
    Planet: "Europa",
    Name: "Abaddon",
    Faction: "Corpus",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "21 - 23",
    TileSet: "Corpus Ice Planet",
  },
  {
    Planet: "Saturn",
    Name: "Cassini",
    Faction: "Grineer",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "21 - 23",
    TileSet: "Grineer Galleon",
  },
  {
    Planet: "Uranus",
    Name: "Ariel",
    Faction: "Grineer",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "25 - 27",
    TileSet: "Grineer Sealab",
  },
  {
    Planet: "Lua",
    Name: "Copernicus",
    Faction: "Corpus",
    CreditReward: 3400,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "25 - 30",
    TileSet: "Orokin Moon",
  },
  {
    Planet: "Neptune",
    Name: "Galatea",
    Faction: "Corpus",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "27 - 29",
    TileSet: "Corpus Outpost",
  },
  {
    Planet: "Pluto",
    Name: "Hydra",
    Faction: "Corpus",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "30 - 34",
    TileSet: "Corpus Ship",
  },
  {
    Planet: "Void",
    Name: "Ukko",
    Faction: "Corrupted",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    DropTableAlias: "VoidCapture3",
    Level: "30 - 35",
    TileSet: "Orokin Tower",
  },
  {
    Planet: "Eris",
    Name: "Isos",
    Faction: "Infested",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    DropTableAlias: "Capture",
    Level: "32 - 36",
    TileSet: "Infested Ship",
  },
];

const assasinationNodes = [
  {
    Planet: "Invasion",
    Name: "Phorid Alert",
    Level: "0 - 0",
    Rewards: "Nyx",
    CreditReward: 0,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Asteroid",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Venus",
    Name: "Fossa",
    Level: "6 - 8",
    Rewards: "Rhino",
    CreditReward: 1500,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Ship",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Mercury",
    Name: "Tolstoj",
    Level: "8 - 10",
    Rewards: "Cronus & Seer",
    CreditReward: 1700,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Asteroid",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Mars",
    Name: "War",
    Level: "11 - 13",
    Rewards: "Excalibur",
    CreditReward: 2000,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Settlement",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Phobos",
    Name: "Iliad",
    Level: "13 - 15",
    Rewards: "Mag",
    CreditReward: 2200,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Ship",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Ceres",
    Name: "Exta",
    Level: "14 - 16",
    Rewards: "Frost, Miter, & Twin Gremlins",
    CreditReward: 2300,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Shipyard",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Jupiter",
    Name: "Themisto",
    Level: "18 - 20",
    Rewards: "Valkyr",
    CreditReward: 2700,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Gas City",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Earth",
    Name: "Oro",
    Level: "20 - 25",
    Rewards: "Hydroid",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Forest",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Deimos",
    Name: "Magnacidium",
    Level: "20 - 25",
    Rewards: "Nekros",
    CreditReward: 2900,
    AdditionalCreditReward: 0,
    TileSet: "Orokin Derelict",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Europa",
    Name: "Naamah",
    Level: "21 - 23",
    Rewards: "Nova",
    CreditReward: 3000,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Ice Planet",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Saturn",
    Name: "Tethys",
    Level: "24 - 26",
    Rewards: "Ember",
    CreditReward: 3300,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Galleon",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Uranus",
    Name: "Titania",
    Level: "27 - 29",
    Rewards: "Equinox",
    CreditReward: 3600,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Sealab",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Neptune",
    Name: "Psamathe",
    Level: "30 - 32",
    Rewards: "Loki",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Ship",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Deimos",
    Name: "Exequias",
    Level: "30 - 35",
    Rewards: "Pathocyst",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    TileSet: "Orokin Derelict",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Eris",
    Name: "Mutalist Alad V Assassinate",
    Level: "30 - 35",
    Rewards: "Mesa",
    CreditReward: 3900,
    AdditionalCreditReward: 0,
    TileSet: "Infested Ship",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Eris",
    Name: "Jordas Golem Assassinate",
    Level: "32 - 34",
    Rewards: "Atlas",
    CreditReward: 4100,
    AdditionalCreditReward: 0,
    TileSet: "Infested Ship",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Sedna",
    Name: "Merrow",
    Level: "35 - 40",
    Rewards: "Saryn & Twin Kohmak",
    CreditReward: 4400,
    AdditionalCreditReward: 0,
    TileSet: "Grineer Asteroid",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Pluto",
    Name: "Hades",
    Level: "35 - 45",
    Rewards: "Trinity",
    CreditReward: 4400,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Outpost",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Jupiter",
    Name: "The Ropalolyst",
    Level: "40 - 40",
    Rewards: "Wisp",
    CreditReward: 4900,
    AdditionalCreditReward: 0,
    TileSet: "Corpus Gas City",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Deimos",
    Name: "Effervo",
    Level: "55 - 60",
    Rewards: "",
    CreditReward: 6400,
    AdditionalCreditReward: 0,
    TileSet: "Albrecht's Laboratories",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Neptune Proxima",
    Name: "Sister of Parvos Confrontation",
    Level: "63 - 70",
    Rewards: "",
    CreditReward: 7200,
    AdditionalCreditReward: 0,
    TileSet: "Free Space",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Saturn Proxima",
    Name: "Kuva Lich Confrontation",
    Level: "63 - 70",
    Rewards: "",
    CreditReward: 7200,
    AdditionalCreditReward: 0,
    TileSet: "Free Space",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Höllvania",
    Name: "Victory Plaza",
    Level: "65 - 70",
    Rewards: "",
    CreditReward: 7400,
    AdditionalCreditReward: 0,
    TileSet: "Höllvania",
    DropTableAlias: "Assasination",
  },
  {
    Planet: "Earth Proxima",
    Name: "Technocyte Coda Concert",
    Level: "100 - 100",
    Rewards: "",
    CreditReward: 10900,
    AdditionalCreditReward: 0,
    TileSet: "Technocyte Coda Stadium",
    DropTableAlias: "Assasination",
  },
];

const assaultMissionNodes = [
  {
    Planet: "Kuva Fortress",
    Name: "Koro",
    Faction: "Grineer",
    CreditReward: 3800,
    AdditionalCreditReward: 0,
    DropTableAlias: "Assault",
    Level: "29 - 31",
    TileSet: "Grineer Asteroid Fortress",
  },
];

const allMissionTypes = [
  volatileMissionNodes,
  survivalMissionNodes,
  spyMissionNodes,
  skirmishMissionNodes,
  sabotageMissionNodes,
  rescueMissionNodes,
  orphixMissionNodes,
  mobileDefenseMissionNodes,
  assasinationNodes,
  assaultMissionNodes,
  captureMissionNodes,
  defenseMissionNodes,
  defectionMissionNodes,
  disruptionMissionNodes,
  excavationMissionNodes,
  faceoffMissionNodes,
  exterminateMissionNodes,
  hijackMissionNodes,
  interceptionMissionNodes,
];

export default allMissionTypes;
